# Generated by Django 5.1.6 on 2025-02-19 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('valid_until', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Модератор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.referralcode', verbose_name='Реферальный код')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
