version: '3.8'

services:
  web:
    ports:
      - "8000:8000"
    build: .
    container_name: referral_system_tz
    volumes:
      - .:/app
    env_file:
      - .env
    command: poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - type: bind
        source: /Users/denisbelenko/docker_data/postgres
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: poetry run celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data: